services:
    - mongodb
    -http-server & sleep 3 & npm run testFunctional & sleep 3
language: node_js
node_js:
    - "4"
    - "6"
before_script:
    - npm install
    - npm run restServer
script:
    - npm test
     
after_script:
    - npm run coveralls

notifications:
  email:
    - lah_spfc2010@hotmail.com
    - isnack.yagami@gmail.com